# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/katlas_raw',
                'doc_host': 'https://sky1ove.github.io',
                'git_url': 'https://github.com/sky1ove/katlas_raw',
                'lib_path': 'katlas_raw'},
  'syms': {}}
